// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw-knOYtK4ylb9N21cUcD7BuaR61xOGsg',
    appId: '1:373820132993:web:92d049d423428bbf328780',
    messagingSenderId: '373820132993',
    projectId: 'amaaiapp',
    authDomain: 'amaaiapp.firebaseapp.com',
    storageBucket: 'amaaiapp.appspot.com',
    measurementId: 'G-149P7H00XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAx9teCyfuAaOrhXC-UmdgDkOsCRLe6gA',
    appId: '1:373820132993:android:4f98ecb7453669b8328780',
    messagingSenderId: '373820132993',
    projectId: 'amaaiapp',
    storageBucket: 'amaaiapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCivlCZ7qhxxzUC6rhk6rwapDQxQlghm7Q',
    appId: '1:373820132993:ios:3d7e4aad4756ed7e328780',
    messagingSenderId: '373820132993',
    projectId: 'amaaiapp',
    storageBucket: 'amaaiapp.appspot.com',
    iosClientId: '373820132993-ef2482tr56duddm3elvl3mf1vpl2o99v.apps.googleusercontent.com',
    iosBundleId: 'com.example.amaAi',
  );
}
